### ISSUE TITLE
Issue while setting up the project

### ISSUE THREAD

**Issue by AnanthaSubramanian** [dotnet-architecture/eShopOnWeb#351]
I downloaded earlier release for .net core 2.1 and started making changes as per the readme file.
I observed an error while running the command. I am pasting the entire errors here-
Microsoft Windows [Version 10.0.17134.1184]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Project\Sonar\Sample Application\.NET Core Applications\eShopOnWeb-netcore2.1\eShopOnWeb-netcore2.1\src\Web>dotnet ef database update -c catalogcontext -p ../Infrastructure/Infrastructure.csproj -s Web.csproj
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.14-servicing-32113 initialized 'CatalogContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=Catalog
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.DesignTimeServiceCollectionExtensions.<>c__DisplayClass1_0.<AddDbContextDesignTimeServices>b__7(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.EnsureServices(IServiceProvider services)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.

C:\Project\Sonar\Sample Application\.NET Core Applications\eShopOnWeb-netcore2.1\eShopOnWeb-netcore2.1\src\Web>

**Comment by AnanthaSubramanian** [comment]
Also, ran into issue when running the command-
C:\Project\Sonar\Sample Application\.NET Core Applications\eShopOnWeb-netcore2.1\eShopOnWeb-netcore2.1\src\Web>dotnet tool restore
Required command was not provided.
Usage: dotnet tool [options] [command]

Options:
  -h, --help   Show command line help.

Commands:
  install <PACKAGE_ID>     Install a tool for use on the command line.
  uninstall <PACKAGE_ID>   Uninstall a tool from the current development environment.
  update <PACKAGE_ID>      Update a tool to the latest stable version.
  list                     List tools installed in the current development environment.

**Comment by fingers10** [comment]
> Entity Framework Core 2.1.14-servicing-32113 **initialized 'CatalogContext' using provider 'Microsoft.EntityFrameworkCore.InMemory'** with options: StoreName=Catalog
> System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. **This is often because no database provider has been configured for this DbContext**.
> 

Looks like you are trying to do migration against `InMemoryDatabase`. 

Make sure you, 
1. comment this [line](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Startup.cs#L43)  (`InMemoryDatabase`)
2. uncomment this [line](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Startup.cs#L46) (`UseSqlServerDatabase`)
3. Select `Infrastructure` project in `Package Manager Console`.
4. `Apply Migrations` and `Update Database`.
5. Now run and see.

**Comment by efleming18** [comment]
Hey @AnanthaSubramanian - it definitely seems like what @fingers10 has pointed out is the issue. (Thanks, @fingers10 for the steps to resolve!). The [initial step](https://github.com/dotnet-architecture/eShopOnWeb#configuring-the-sample-to-use-sql-server) is also in the README to switch it from InMemory to SQL Server.

After this change, please let me know if it is still not working and we can investigate further.

**Comment by efleming18** [comment]
Hey @AnanthaSubramanian - have you had a chance to give this a try yet?

**Comment by AnanthaSubramanian** [comment]
Hi Fleming,

I haven't been able to take a look at the suggestions.
I will take couple of days to try out the suggestions as I am occupied with something else at this moment. I shall revert on this as soon as I try out the suggestions.

Thanks for following up.

Regards,
Anantha

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by efleming18** [comment]
Hey @AnanthaSubramanian  - I'm going to close this issue. If something comes up and you're still having issues, or a new issue feel free to create a new issue on the repo! Hopefully it worked for you.
