### ISSUE TITLE
/Admin Manage Product Catalog Create New got exception

### ISSUE THREAD

**Issue by LeiYangGH** [dotnet-architecture/eShopOnWeb#547]
1. Clone repo
2. cd src/Web
3. dotnet run(uses in memory db by default)
4. login with admin, then go to 1/Admin, try to add one product catelog, since the list is empty.

Expected: show some form to input data.
Actual: No effects. in developer console got the exceptions:
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Sequence contains no elements
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[CatalogType](IEnumerable`1 source)
   at BlazorAdmin.Pages.CatalogItemPage.Create.Open() in C:\G\eShopOnWeb\src\BlazorAdmin\Pages\CatalogItemPage\Create.razor:line 138
   at BlazorAdmin.Pages.CatalogItemPage.List.CreateClick() in C:\G\eShopOnWeb\src\BlazorAdmin\Pages\CatalogItemPage\List.razor.cs:line 50
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by khairuzzaman** [comment]
I have also faced the problem when running the application from the visual studio in IIS Express. I found that the PublicApi project is running in SSL port 44339 but the appsettings of BlazorAdmin project is use port 5099 to consume PublicApi. So I change the appsettings with the correct port and now it is working properly.

// appsettings.Development.json

```
{
  "baseUrls": {
    "apiBase": "https://localhost:44339/api/",
    "webBase": "https://localhost:44315/"
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "System": "Warning"
    }
  }
}
```

**Comment by michelcedric** [comment]
I created a Pull request to fix that, There a mix in configuration to use IIS profile in certain case.
https://github.com/dotnet-architecture/eShopOnWeb/pull/552
The port depend if you start in IIS Profile or Console.
You can in command line add --launch-Profile Web => Web is the name of the profile find in https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Web/Properties/launchSettings.json#L20
