### ISSUE TITLE
All Public API endpoints contains thread racing error

### ISSUE THREAD

**Issue by kuda1978** [dotnet-architecture/eShopOnWeb#826]
The problem can result several exceptions being thrown:
1. ObjctDisposedException
2. EF Core Exception
```
System.InvalidOperationException
  HResult=0x80131509
  Message=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at Ardalis.Specification.EntityFrameworkCore.RepositoryBase`1.<ListAsync>d__18.MoveNext()
   at Microsoft.eShopWeb.PublicApi.CatalogBrandEndpoints.CatalogBrandListEndpoint.<HandleAsync>d__5.MoveNext() in C:\work\GitHub\eShopOnWeb\src\PublicApi\CatalogBrandEndpoints\CatalogBrandListEndpoint.cs:line 45

  This exception was originally thrown at this call stack:
    Microsoft.EntityFrameworkCore.DbContext.ContextServices.get()
    Microsoft.EntityFrameworkCore.DbContext.DbContextDependencies.get()
    Microsoft.EntityFrameworkCore.DbContext.Set<TEntity>()
    Ardalis.Specification.EntityFrameworkCore.RepositoryBase<T>.ListAsync(System.Threading.CancellationToken)
    Microsoft.eShopWeb.PublicApi.CatalogBrandEndpoints.CatalogBrandListEndpoint.HandleAsync() in CatalogBrandListEndpoint.cs
```

**Comment by ardalis** [comment]
How does one reproduce this exception?

**Comment by kuda1978** [comment]
Steps to reproduce:
1. Add delay in method `CatalogBrandListEndpoint.HandleAsync`
```
public async Task<IResult> HandleAsync()
{
    await Task.Delay(1000);
    ...
```
2. Run `PublicApi`
3. Run few requests to the endpoint in parallel
```
for /L %%a in (1,1,5) do (
  start curl -X GET https://localhost:44339/api/catalog-brands
)
```

As I realize, Single instance of CatalogBrandListEndpoint register as endpoint, but private field _catalogBrandRepository assigned from every request scope service provider. If we request endpoint several times in parallel we can not determinate in this field store instance from our request scope or from another one.

**Comment by michelcedric** [comment]
Hi
I knew the issue but forgot to update in this repository.
https://github.com/michelcedric/StructuredMinimalApi/issues/28
I will update and ifx this in a few days.
